apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  name: clientk8spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientk8spark
  template:
    metadata:
      labels:
        app: clientk8spark
    spec:
      serviceAccountName: spark-sa
      automountServiceAccountToken: true    
      containers:
      - image: fchapuzot/dockergitk8sclient:0.0.4
        imagePullPolicy: Always
        name: client
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler

